In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/GrandmaCan/ML/main/Classification/Diabetes_Data.csv"
data = pd.read_csv(url)
data

Age  Weight  BloodSugar Gender  Diabetes
0     25     119       130.8     男生         1
1     66     102       128.1     女生         1
2     59      65       103.9     男生         0
3     46     117        94.8     女生         0
4     45      79        57.8     男生         0
..   ...     ...         ...    ...       ...
395   72      63        97.1     女生         0
396   22     117       156.7     女生         1
397   31      76       119.0     男生         0
398   36      65        96.3     女生         1
399   38      75       106.3     男生         0

[400 rows x 5 columns]

In [2]:
data['Gender'] = data['Gender'].map({'男生':1, '女生':0})
data

Age  Weight  BloodSugar  Gender  Diabetes
0     25     119       130.8       1         1
1     66     102       128.1       0         1
2     59      65       103.9       1         0
3     46     117        94.8       0         0
4     45      79        57.8       1         0
..   ...     ...         ...     ...       ...
395   72      63        97.1       0         0
396   22     117       156.7       0         1
397   31      76       119.0       1         0
398   36      65        96.3       0         1
399   38      75       106.3       1         0

[400 rows x 5 columns]

In [4]:
# 將資料拆分 訓練集、測試集
from sklearn.model_selection import train_test_split
x = data[["Age", "Weight", "BloodSugar", "Gender"]]
y = data["Diabetes"]

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=87)
x_train = x_train.to_numpy()
x_test = x_test.to_numpy()

(array([[ 47. ,  78. , 112.7,   1. ],
        [ 41. ,  79. ,  90.5,   1. ],
        [ 28. ,  74. ,  96.4,   0. ],
        ...,
        [ 44. ,  53. , 122.2,   1. ],
        [ 42. ,  47. ,  69.7,   1. ],
        [ 69. , 101. ,  97. ,   0. ]]),
 array([[ 74. , 103. , 127.9,   0. ],
        [ 73. ,  74. , 106.1,   0. ],
        [ 77. ,  65. ,  52. ,   1. ],
        [ 22. , 107. , 110. ,   1. ],
        [ 31. , 104. ,  98.2,   1. ],
        [ 77. ,  47. ,  84.7,   1. ],
        [ 50. ,  48. , 103.8,   0. ],
        [ 79. ,  87. , 148.4,   0. ],
        [ 29. , 106. , 102.8,   1. ],
        [ 64. ,  98. , 134. ,   1. ],
        [ 27. ,  74. , 115. ,   1. ],
        [ 29. ,  81. ,  88.1,   0. ],
        [ 45. ,  79. ,  57.8,   1. ],
        [ 47. , 106. ,  93.3,   0. ],
        [ 60. , 116. , 113.5,   1. ],
        [ 63. ,  74. , 102.3,   0. ],
        [ 59. ,  65. , 103.9,   1. ],
        [ 53. , 107. ,  79. ,   1. ],
        [ 52. ,  42. ,  80.5,   0. ],
        [ 66. ,  62. ,  72.7,   1. 

In [5]:
# 特徵縮放
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(x_train)
x_train = scaler.transform(x_train)
x_test = scaler.transform(x_test)

x_test

array([[ 1.4964114 ,  0.95077942,  1.01425033, -1.06458129],
       [ 1.43615575, -0.2915795 ,  0.06547324, -1.06458129],
       [ 1.67717835, -0.67713916, -2.28906075,  0.93933644],
       [-1.63688239,  1.12213927,  0.23520859,  0.93933644],
       [-1.09458154,  0.99361938, -0.27834966,  0.93933644],
       [ 1.67717835, -1.44825849, -0.86589511,  0.93933644],
       [ 0.05027581, -1.40541853, -0.0346271 , -1.06458129],
       [ 1.79768965,  0.26534002,  1.90644898, -1.06458129],
       [-1.21509284,  1.07929931, -0.07814898,  0.93933644],
       [ 0.89385491,  0.73657961,  1.27973383,  0.93933644],
       [-1.33560414, -0.2915795 ,  0.45281801,  0.93933644],
       [-1.21509284,  0.00830024, -0.7179207 , -1.06458129],
       [-0.25100244, -0.07737968, -2.03663381,  0.93933644],
       [-0.13049114,  1.07929931, -0.49160689, -1.06458129],
       [ 0.65283231,  1.50769894,  0.38753519,  0.93933644],
       [ 0.83359926, -0.2915795 , -0.09990993, -1.06458129],
       [ 0.59257666, -0.

In [6]:
import numpy as np
# 帶入函數
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [8]:
import numpy as np

w = np.array([1,2,3,4])
b = 1

z = (w*x_train).sum(axis=1) +b

sigmoid(z)

array([9.95698875e-01, 9.06375097e-01, 2.05197222e-03, 9.99871937e-01,
       9.99976601e-01, 9.99597573e-01, 9.42501826e-03, 6.58750315e-01,
       9.72220502e-01, 2.04535575e-03, 9.95406153e-01, 9.33440694e-01,
       9.99020890e-01, 6.88676986e-03, 8.77843224e-05, 7.26538573e-01,
       9.32368144e-01, 8.09433980e-02, 1.22884071e-02, 6.59095116e-01,
       9.35714906e-01, 6.38508320e-02, 3.04389233e-01, 9.30273981e-01,
       1.23897708e-03, 9.93625786e-01, 5.90053392e-02, 9.86068856e-01,
       1.89102010e-04, 1.33090984e-03, 8.85296779e-01, 9.99482973e-01,
       4.70219520e-04, 9.99353194e-01, 1.87660501e-01, 9.95430646e-01,
       9.98245826e-01, 9.99905804e-01, 9.77808458e-01, 4.92634254e-03,
       9.98319405e-01, 9.99759816e-01, 1.56719013e-01, 4.11932567e-01,
       1.47183312e-01, 8.92262698e-01, 9.92187079e-01, 1.02910854e-01,
       8.61895492e-01, 5.88617508e-02, 9.36987924e-02, 3.51332925e-01,
       9.22153819e-01, 2.12994568e-02, 6.66132695e-01, 9.13035739e-01,
      